version: "3.9"
services:
  api:
    container_name: media-translator
    build: .
    image: media-translator:dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped
    user: "1000:1000" # ensure container runs as webapp user id on host too
